### ISSUE TITLE
Zero Push Beam file needed for Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by vickydhas** [SymmetricInfinity/mod_zeropush#3]
Hello All,

I am trying to use this to create a beam file from my ubuntu server with erlang and MongooseIm version mentioned below.

I am getting some errors and have raised this to MongooseIm github guys.

In mean time I see there is already a beam file given by these developers. If I insert this in the `~/mim/MongooseIM/rel/mongooseim/lib/ejabberd-2.1.8+mim-2.0.0beta2-284-g2786b03/ebin$` Location I am able to add this code for mod push in ejabberd.cfg.

```
{mod_zeropush, [
    {sound, "default"},
    {auth_token, "ocbc-chat-token"},
    {post_url, "http://ec223.353.43.4-212.ap-southeast-1.compute.amazonaws.com/MyAppChatPN/MyAppChatService.svc"}
  ]}.
```

How to check if really this Mod_zeroPush is not working on MIM side not server as server says its not getting the request.

Can I get some directions how to add this to my MongooseIM server.

MongooseIM version : `MongooseIM version 2.0.0beta2-284-g2786b03`
Erlang Version : `Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]`

Note : I have used the below beam file and put in the above `~/mim....ebin directory` and receoived no error but don't know if tis really sending the post request from Mongoose Chat

**Comment by adamvduke** [comment]
Hi @vickydhas, this repository was moved about 2 years ago to https://github.com/ZeroPush/mod_zeropush, and ZeroPush was sunset in February of 2016. You may be interested in this other similar module that allows posting to a configurable URL. https://github.com/adamvduke/mod_interact

Unfortunately, I don't have time to maintain this module, but the code should get you moving in the right direction.

**Comment by vickydhas** [comment]
I added this with your advice AADI in module and can see the module loaded in the mongooseimctl debug window.

Appreciate your help over this.

```{mod_zeropush, [ {sound, "default"}, {auth_token, "your-auth-token"}, {post_url, "https://api.zeropush.com/broadcast"} ]}```

Closing this request
